version: 2
jobs:
  build:
    docker:
      - image: gnuton/asuswrt-merlin-toolchains-docker
        environment:
          MAKEFLAGS: "-j 1"
          PROJECT_DIR: "/root/project"
    steps:
      - checkout
      - run:
          name: Set EXTENDNO
          shell: /bin/bash
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "Nothing to do. Not a release."
            else
              EXT_TAG="$(echo -n $CIRCLE_TAG | sed -e "s/[0-9.]\\+\\-//g")"
              sed -i "s/EXTENDNO=.*/EXTENDNO=${EXT_TAG}/g" release/src-rt/version.conf
            fi
      - run:
          name: Generate changelog (for snapshots only now)
          command: |
            REGXP_TO_MATCH=.*gnuton.*
            if [[ ${CIRCLE_TAG} =~ ${REGXP_TO_MATCH} ]]; then 
              CURRENT_TAG=$(git tag --sort=-version:refname | grep ${REGXP_TO_MATCH} | head -n 1)
              PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v snapshot | grep ${REGXP_TO_MATCH} | head -n 2 | sed -n 2p)
              git log ${PREVIOUS_TAG}...${CURRENT_TAG} --pretty=format:'* %s' --reverse | grep -v 'Merge branch' > /tmp/CHANGELOG
              echo $CHANGELOG
            else 
              echo "No changelog to generate. Changelog is generated only for tags matching ${REGXP_TO_MATCH}";
            fi;
      - run:
          name: Setup toolchain
          command: |
            rm ${PROJECT_DIR}/release/src-rt-6.x.4708/toolchains
            ln -s /opt/am-toolchains/brcm-arm-sdk  ${PROJECT_DIR}/release/src-rt-6.x.4708/toolchains
      - run:
          name: Build firmware
          shell: /bin/bash
          no_output_timeout: 120m
          command: | 
            cd ${PROJECT_DIR}/release/src-rt-6.x.4708/
            ls
            pwd
            make clean || echo "maybe already clean, so if it fails please continue"
            #X make dsl-ac68u | tee "/tmp/build.log" # | grep -i "error\|-e"
            #X ls ${PROJECT_DIR}/release/src-rt-6.x.4708/image/

      - run:
          name: Prepare workspace
          command: |
            mkdir -p workspace/release
            #X cp ${PROJECT_DIR}/release/src-rt-6.x.4708/image/*.trx workspace/release
            #X cp ${PROJECT_DIR}/release/src-rt-6.x.4708/image/*.md5 workspace/release
            #X cp /tmp/build.log workspace/release
             if [ -z "${CIRCLE_TAG}" ]; then
              echo "No CHANGELOG to copy. Not a release build."
            else
              cp -f /tmp/CHANGELOG workspace/release
            fi
      - persist_to_workspace:
          root: workspace
          paths:
            - release
  publish-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish Release on Github"
          command: |
            echo "Uploading release:${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} workspace/release/
  publish-github-ci-pre-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish CI pre-release on Github"
          command: |
            echo "Uploading CI pre-release..."
            RELEASE_TITLE="Snapshot: ${CIRCLE_TAG}"
            RELEASE_BODY="This is an experimental build. Please check the CHANGELOG for more info."
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "${RELEASE_TITLE}" -b "${RELEASE_BODY}" -delete -prerelease ${CIRCLE_TAG} workspace/release/
 
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
               - master
               - mainline
      - publish-github-release:
          filters:
            tags:
              only: /[0-9]+.*gnuton.*/
            branches:
              ignore: /.*/
          requires:
            - build
      - publish-github-ci-pre-release:
          filters:
            tags:
              only: /gnuton-snapshot-.*/ 
            branches:
              ignore: /.*/
          requires:
            - build
